---

- name: Add homebrew versions repo
  homebrew_tap: tap=homebrew/versions state=present

- name: Install common tools
  homebrew: name={{item}}
  with_items:
    - gcc
    - tmux
    - tree
    - zsh
    - fasd
    - wget
    - dos2unix
    - xz
    - md5sha1sum
    - htop-osx
    - bash-completion
    - imagemagick
    - httpie
    - ssh-copy-id
    - watch
    - nmap
    - sysdig
    - jq
    - thefuck
    - gnu-sed
    - coreutils
    - bash
    - shunit2
    - vault

- name: Install common binary tools
  homebrew_cask: name={{item}}
  ignore_errors: yes
  with_items:
    - google-hangouts
    - firefox
    - google-chrome
    - iterm2
    - sublime-text
    - macdown
    - atom
    - dash
    - disk-inventory-x
    - keepassx
    - mattermost


- name: generate .bash_profile from .bash_profile.j2
  template: src=.bash_profile.j2 dest=~/.bash_profile

- name: generate launchd.conf from launchd.conf.j2
  become: yes
  template: src=launchd.conf.j2 dest=/etc/launchd.conf

- name: Ensure local hostname is in /etc/hosts
  become: yes
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ ansible_env.DEV_HOSTNAME }}"

- name: Ensure HostName is set
  become: yes
  shell: scutil --set HostName {{ ansible_env.DEV_HOSTNAME }}

- name: Ensure LocalHostName is set
  become: yes
  shell: scutil --set LocalHostName {{ ansible_env.DEV_HOSTNAME }}

- name: Ensure ComputerName is set
  become: yes
  shell: scutil --set ComputerName {{ ansible_env.DEV_HOSTNAME }}
