---

- name: Add homebrew versions repo
  homebrew_tap: tap=homebrew/versions state=present

- name: Add homebrew cask repo
  homebrew_tap: tap=caskroom/cask state=present

- name: Add homebrew cask versions repo
  homebrew_tap: tap=caskroom/versions state=present

- name: Install homebrew cask
  homebrew: name=brew-cask

- name: Install common tools
  homebrew: name={{item}}
  with_items:
    - gcc
    - tmux
    - tree
    - zsh
    - fasd
    - wget
    - dos2unix
    - xz
    - md5sha1sum
    - htop-osx
    - bash-completion
    - imagemagick
    - httpie
    - ssh-copy-id
    - watch
    - nmap
    - sysdig

- name: Install common binary tools
  homebrew_cask: name={{item}}
  with_items:
    - hipchat
    - adium
    - teamviewer
    - skype
    - google-hangouts
    - firefox
    - thunderbird
    - google-chrome
    - google-chrome-canary
    - iterm2
    - sublime-text
    - macdown
    - atom
    - dropbox
    - google-drive
    - dash
    - disk-inventory-x


# TODO remove since this is not necessary
#
#- name: Ensure local hostname is in /etc/hosts
#  sudo: yes
#  lineinfile:
#    dest: "/etc/hosts"
#    line: "127.0.0.1 jfischer-mac"
#
#- name: Ensure HostName is set
#  sudo: yes
#  shell: scutil --set HostName jfischer-mac
#
#- name: Ensure LocalHostName is set
#  sudo: yes
#  shell: scutil --set LocalHostName jfischer-mac
#
#- name: Ensure ComputerName is set
#  sudo: yes
#  shell: scutil --set ComputerName jfischer-mac




# TODO remove
#- name: Ensure .bash_profile is present
#  sudo: no
#  copy:
#    src: .bash_profile
#    dest: "~/.bash_profile"
#
- name: generate .bash_profile from .bash_profile.j2
  template: src=.bash_profile.j2 dest=~/.bash_profile


- name: generate launchd.conf from launchd.conf.j2
  sudo: yes
  template: src=launchd.conf.j2 dest=/etc/launchd.conf

  
#TODO disabled temporarely  
#- name: Ensure launchd.conf is present
#  sudo: yes
#  copy:
#    src: /tmp/launchd.conf
#    dest: "/etc/launchd.conf"#

