- name: Install maven
  homebrew: name=maven

- name: Ensure local maven directory is present
  file:
    path: "~/.m2"
    state: directory

- name: Ensure maven settings are present
  copy:
    src: settings.xml
    dest: "~/.m2/settings.xml"

- name: Ensure maven settings with mirror are present
  copy:
    src: settings-mirror.xml
    dest: "~/.m2/settings-mirror.xml"

#- name: Ensure mavenrc is present
#  copy:
#   src: mavenrc
#    dest: "~/.mavenrc"
